### ISSUE TITLE
Car Unlock and Lock sounds

### ISSUE THREAD

**Issue by GetSomePanda** [GetSomePanda/HeroesOfGaming-4.0#18]
I'll do this so that the sound will play over the network so others that are nearby will hear the sound.

**Comment by ConnorSoap** [comment]
Added but won't work for some reason, probably missed something.

**Comment by GetSomePanda** [comment]
Fixed. https://github.com/GetSomePanda/HeroesOfGaming-4.0/commit/3053681ba8b7f9ec8d693d5f770083dfdb6d615a
