### ISSUE TITLE
Vote Admin + Kick Works (DISABLE THIS)

### ISSUE THREAD

**Issue by Cocaina-Ricky** [GetSomePanda/HeroesOfGaming-4.0#26]
This needs disabling

**Comment by ConnorSoap** [comment]
You have to do this in server.cfg I believ, add allowedVoteCmds[] = {}; in server.cfg

**Comment by Cocaina-Ricky** [comment]
Will add soon.

**Comment by GetSomePanda** [comment]
Yes this is the method.
